#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bin=$(dirname -- "${BASH_SOURCE-$0}")
bin=$(cd -- "$bin"; pwd)

DEFAULT_LIBEXEC_DIR=$bin/../libexec
OCTOPUS_LIBEXEC_DIR=${OCTOPUS_LIBEXEC_DIR:-$DEFAULT_LIBEXEC_DIR}
. "$OCTOPUS_LIBEXEC_DIR/octopus-config.sh"

print_usage() {
    cat <<EOF
Usage: octopus [--config conf-dir] COMMAND
where COMMAND is one of:
  classpath     print the class path needed to get the Octopus jar
                and the required libraries
  master        run a Octopus master
  octaline      run a Octopus interactive terminal
Most commands print help when invoked without parameters.
EOF
}

if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

COMMAND=$1
shift
case $COMMAND in
    -h|--help|-help)
        print_usage
        exit
        ;;
    classpath)
        echo $CLASSPATH
        ;;
    *)
        for cmd in "$bin"/cmd/*.sh; do
            . "$cmd"
        done

        found=false
        for cmd in $COMMAND_LIST; do
            if [ "$cmd" = "$COMMAND" ]; then
                found=true
                break
            fi
        done

        if [ "$found" = false ]; then
            echo "COMMAND $COMMAND not found"
            exit 1
        fi

        export CLASSPATH
        "$COMMAND" "$@"
esac
